Выполнена разметка главной страницы
htmlacademy-htmlcss/1875067-device-32 pull request #2
Opened 2021-09-29 18:03 UTC by NadiCher

2021-09-30 17:15 UTC, mouxez requested changes

2021-09-30 17:15 UTC, mouxez commented on index.html
> +      <h1 class="hidden">Интернет-магазин гаджетов "Девайс"</h1>
это называется visually-hidden
https://htmlacademy.ru/blog/boost/frontend/short-12

2021-09-30 17:15 UTC, mouxez commented on index.html
> +            <a class="categories-link">
у ссылок есть обязательный атрибут href
желательно добавлять им так же title

2021-09-30 17:15 UTC, mouxez commented on index.html
> +              <img class="categories-img" src="" alt="">
alt не надо оставлять пустым, везде надо указать название в нём

2021-10-02 14:13 UTC, NadiCher commented on index.html
> +            <a class="categories-link">
href добавила. Нужно ли добавлять title, если он дублирует текст ссылки? Название категории товаров, например.

2021-10-02 14:13 UTC, NadiCher commented on index.html
> +              <img class="categories-img" src="" alt="">
Андрей на лайве говорил, что если есть картинка и заголовок к ней, тогда не нужно заполнять alt, т.к. он будет дублировать текст заголовка. Как все же лучше сделать?

2021-10-02 14:13 UTC, NadiCher commented on index.html
> +      <h1 class="hidden">Интернет-магазин гаджетов "Девайс"</h1>
Исправила. Название класса стандартное или просто так принято в академии?

2021-10-02 18:13 UTC, mouxez commented on index.html
> +      <h1 class="hidden">Интернет-магазин гаджетов "Девайс"</h1>
это принятый в сообществе программистов класс

2021-10-02 18:14 UTC, mouxez commented on index.html
> +            <a class="categories-link">
как правило нужно. это надо для скринридеров и поисковых роботов

2021-10-02 18:15 UTC, mouxez commented on index.html
> +              <img class="categories-img" src="" alt="">
это как тебе удобно. я просто рекомендую везде ставить, чтобы не забыть где-то поставить.

2021-10-03 06:58 UTC, NadiCher commented on index.html
> +      <h1 class="hidden">Интернет-магазин гаджетов "Девайс"</h1>
Ок

2021-10-03 06:58 UTC, NadiCher commented on index.html
> +            <a class="categories-link">
Добавила

2021-10-03 06:59 UTC, NadiCher commented on index.html
> +              <img class="categories-img" src="" alt="">
Ок, поняла

2021-10-05 06:57 UTC, merged